config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :reviews, except: [:show] do
      resources :comments
    end
  end

  get 'about' => 'mainpage#about'

  get 'show' => 'reviews#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mainpage#index'

  get 'index' => 'mainpage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def destroy
    @review = Review.find(params[:review_id])
    comment = @review.comments.find(params[:id])

    if comment.destroy
      flash[:notice] = "Comment was deleted."
      redirect_to edit_movie_review_path(@review.movie, @review)
    else
      flash[:alert] = "Comment couldn't be deleted. Try again."
      redirect_to edit_movie_review_path(@review.movie, @review)
    end
  end

  def create
# #11
    @review = Review.find(params[:review_id])
    comment = @review.comments.new(comment_params)

    if comment.save
      flash[:notice] = "Comment saved successfully."
      redirect_to edit_movie_review_path(@review.movie, @review)
    else
      flash[:alert] = "Comment failed to save."
      redirect_to edit_movie_review_path(@review.movie, @review)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :name)
  end
end

app/controllers/mainpage_controller.rb
require 'will_paginate/array'

class MainpageController < ApplicationController
  helper_method :sort_direction
  def index
    total = 0
    #@movies = Movie.order(params[:sort])
    @movies = Movie.paginate(:page => params[:page], :per_page => 10).order(params[:sort])
    @reviews = Review.all
    @movies.each do |x|
      if x.reviews.length != 0
        x.reviews.each do |y|
          if y.score != nil
            total = total + y.score
          end
        end
        x.rating = (total / x.reviews.length)
      end
      total = 0
    end
    @recent_movies = Movie.order('release_date DESC')
    @recent_movies.each do |x|
      if x.reviews.length != 0
        x.reviews.each do |y|
          if y.score != nil
            total = total + y.score
          end
        end
        x.rating = (total / x.reviews.length)
      end
      total = 0
    end
  end

  def about
  end

  private
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    total = 0
    @movies = Movie.paginate(:page => params[:page], :per_page => 15)
    @movies.each do |x|
      if x.reviews.length != 0
        x.reviews.each do |y|
          if y.score != nil
            total = total + y.score
          end
        end
        x.rating = (total / x.reviews.length)
      end
      total = 0
    end
  end
  def show
    total = 0
    @movie = Movie.find(params[:id])
    if @movie.reviews.length != 0
      @movie.reviews.each do |y|
        if y.score != nil
          total = total + y.score
        end
      end
      @movie.rating = (total / @movie.reviews.length)
    end
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

  end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new

  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)

    if @review.save
      flash[:notice] = "Review was saved."
      redirect_to index_path
    else
      flash.now[:alert] = "There was an error saving the review. Please try again."
      render :new
    end

  end
  def edit
    @review = Review.find(params[:id])
  end

  def show
    @reviews = Review.paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
  end
  private

  def review_params
    params.require(:review).permit(:score, :body, :reviewer, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title, column, direction)
    direction = sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == 'desc' ? 'down' : 'up'

    link_to index_path, class: 'tiny button secondary', id: column do
      "#{title} &nbsp; <i class=fi-arrow-#{icon}></i>".html_safe
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comments/_comment.html.erb
<%= content_tag :div, class: 'media', id: "comment-#{comment.id}" do %>
   <div class="media-body">
     <p><%= comment.body %></p>
     <small>
       <%= comment.name %> commented <%= time_ago_in_words(comment.created_at) %> ago
         <%= link_to "Delete", [comment.review.movie, comment.review, comment], method: :delete %>
     </small>
   </div>
   <hr>
<% end %>

app/views/comments/_form.html.erb
<h4>Add a comment</h4>
 <%= form_for [movie, review, comment] do |f| %>
  <form class="form-horizontal">
   <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control', style: 'width: 150px', placeholder: "Enter a name" %>
   </div>
   <div class="form-group">
     <%= f.label :body%>
     <%= f.text_field :body, class: 'form-control pull-right', placeholder: "Enter a new comment" %>
   </div>
   <div class="form-group">
   <%= f.submit "Submit Comment", class: 'btn btn-default pull-right' %>
 </div>
 </form>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie DataBase</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to "Reviews", show_path %></li>
        <li><%= link_to "About", about_path %></li>
        <h3 align="right", style="padding-right:10dp"> MovieGo</h3>
      </ul>
      <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
      <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/mainpage/about.html.erb
<h1>About</h1>
<p>This application pulls data from movie database with API call
With developed movie database on client side, user is able to write reviews
and comments of existing reviews with star rating.</p>

app/views/mainpage/index.html.erb
<div class="modal-body row">
  <div class="col-md-6", style="padding-left:0">
    <div class="container", style="padding-left:0">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
              <div class="form-inline">
                  <h5>Sort by:
                  <%= link_to "Title", class: "btn btn-primary btn-md", sort: "title DESC"%>,
                  <%= link_to "Released date", class: "btn btn-primary btn-md", sort: "release_date DESC"%>,
                  <%= link_to "Genre", sort: "genre DESC", class: "btn btn-primary btn-md"%> </h5>
              </div>
            </div>
          </div>
      </div>
    </div>
    <% @movies.each do |movie| %>
      <%= render partial: 'movies/post', locals: { movie: movie } %>
    <% end %>
    <%= will_paginate @movies %>
  </div>
  <div class="col-md-4", style="padding-left:0">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
              <h3> Recent Reviews </h3>
              <% for i in 0..3 %>
                <div class="media">
                  <div class="media-body">
                    <h6 class="media-heading">
                      <div class="reviews">
                        <p class="inline">
                          <%= link_to "#{@reviews[@reviews.length-1-i].body}", edit_movie_review_path(@reviews[@reviews.length-1-i].movie, @reviews[@reviews.length-1-i]) %>
                        <div class="star-rating" data-score= <%= @reviews[@reviews.length-1-i].score %> ></div></p>
                      </div>
                      <medium>Title - <%= @reviews[@reviews.length-1-i].movie.title %></medium>
                      <hr style="height:1px">
                    </h6>
                  </div>
                </div>
              <% end %>
              <%= link_to "View all Reviews", show_path, class: "btn btn-primary btn-xs" %>
            </div>
          </div>
        </div>
      </div>
   <!-- Your second column here -->
   <div class="container">
     <div class="row">
       <div class="col-xs-12 col-sm-6 col-md-6">
           <div class="well well-sm">
             <h3> Recent Movies </h3>
               <% for i in 0..3 %>
                 <div class="media">
                   <div class="media-body">
                     <h6 class="media-heading">
                       <div class="reviews">
                         Title - <%= @recent_movies[i].title %>
                         <div class="star-rating" data-score= <%= @recent_movies[i].rating %> >
                         </div>
                       </div>
                       <hr style="height:1px">
                     </h6>
                   </div>
                 </div>
               <% end %>
               <%= link_to "View all Movies", movies_path, class: "btn btn-primary btn-xs" %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/_post.html.erb
<div class="container", style="padding-left:0">
   <div class="row">
       <div class="col-xs-12 col-sm-6 col-md-6">
           <div class="well well-sm">
               <div class="row">
                   <div class="col-sm-6 col-md-4">
                       <img src="<%= movie.image_url %>"  alt="" class="img-rounded img-responsive" />
                       <div class="star-rating", style="padding-left: 13px;", data-score= <%= movie.rating %> >
                       </div>
                   </div>
                   <div class="col-sm-6 col-md-8">
                       <h4><%= link_to "#{movie.title}", movie_path(movie) %></h4>
                       <p>
                           <i class="glyphicon glyphicon-gift"></i><%= movie.release_date %>
                           <br/>
                           <i class="glyphicon glyphicon-gift"></i><%= movie.genre %>
                       </p>
                       <!-- Split button -->
                       <%= link_to "Write a review", new_movie_review_path(movie), class: "btn btn-primary btn-xs" %>
                       <% for i in 0..1 %>
                         <div class="media">
                           <div class="media-body">
                             <h6 class="media-heading">
                               <div class="reviews">
                                 <% if movie.reviews[movie.reviews.length-1-i] != nil %>
                                   <div class="star-rating" data-score= <%= movie.reviews[movie.reviews.length-1-i].score %> >
                                   </div>
                                   <%= movie.reviews[movie.reviews.length-1-i].body %> - <%= movie.reviews[movie.reviews.length-1-i].reviewer %>
                                 <% end %>
                               </div>
                             </h6>
                           </div>
                         </div>
                       <% end %>
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/movies/index.html.erb
<br>
<% @movies.each do |movie| %>
  <%= render partial: 'post', locals: { movie: movie } %>
<% end %>
<%= will_paginate @movies %>

app/views/movies/show.html.erb
<div class="container", style="padding-left:0">
   <div class="row">
       <div class="col-xs-12 col-sm-6 col-md-6">
           <div class="well well-sm">
               <div class="row">
                   <div class="col-sm-6 col-md-4">
                       <img src="<%= @movie.image_url %>"  alt="" class="img-rounded img-responsive" />
                       <div class="star-rating", style="padding-left: 13px;", data-score= <%= @movie.rating %> >
                       </div>
                   </div>
                   <div class="col-sm-6 col-md-8">
                       <h4><%= @movie.title %></h4>
                       <p>
                           <i class="glyphicon glyphicon-gift"></i><%= @movie.release_date %>
                           <br/>
                           <i class="glyphicon glyphicon-gift"></i><%= @movie.genre %>
                       </p>
                       <!-- Split button -->
                       <%= link_to "Write a review", new_movie_review_path(@movie), class: "btn btn-primary btn-xs" %>
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>

<% @movie.reviews.paginate(:page => params[:page], :per_page => 10).order('created_at DESC').each do |x| %>
  <div class="reviews">
    <p class="inline"><%= link_to "#{x.body}", edit_movie_review_path(@movie, x)  %>
    <div class="star-rating" data-score= <%= x.score %> ></div></p>
    <small>
      Title - <%= x.movie.title %>
      <br>
      Reviewer - <%= x.reviewer %>
      <br>
      Email - <%= x.email %>
      <br>
      Created at - <%= x.created_at %>
      <hr style="height:1px">
    </small>
  </div>
<% end %>
<%= will_paginate @movie.reviews.paginate(:page => params[:page], :per_page => 10).order('created_at DESC') %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for [@movie, @review], url: {action: "create"} do |f| %>
<% if @review.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(@review.errors.count, "error") %>.</h4>
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group row">
  <%= f.label :score, class: 'col-sm-2 form-control-label' %>
<div class="col-sm-6" id='star-rating'></div>
</div>

<%= f.label :reviewer %>
<%= f.text_field :reviewer, class: 'form-control', placeholder: "Enter reviewer" %>


<%= f.label :email %>
<%= f.text_field :email, class: 'form-control', placeholder: "Enter email" %>


<%= f.label :body %>
<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter body" %>

<br/>
<div class="form-group row">
  <div class="col-sm-10">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to "Back", index_path, class: "btn btn-secondary" %>
  </div>
</div>
<% end %>
<script>
$('#star-rating').raty({
	path: '/assets',
	scoreName: 'review[score]'
});
</script>

app/views/reviews/_view.html.erb
<div class="media">
  <div class="media-body">
    <h6 class="media-heading">
      <div class="reviews">
        <p class="inline">
          <%= link_to "#{@review.body}", view_path %>
        <div class="star-rating" data-score= <%= @review.score %> ></div></p>
      </div>
      <br>
      <small>
      Title - <%= @review.movie.title %>
      <br>
      Reviewer - <%= @review.reviewer %>
      <br>
      Email - <%= @review.email %>
      <br>
      Created at - <%= @review.created_at %>
      <hr style="height:1px">
    </small>
    </h6>
  </div>
</div>
<%= render @review.comments %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/edit.html.erb
<div class="media">
  <div class="media-body">
    <h6 class="media-heading">
      <div class="reviews">
        <p class="inline">
          <%= @review.body %>
        <div class="star-rating" data-score= <%= @review.score %> ></div></p>
      </div>
      <br>
      <small>
      Title - <%= @review.movie.title %>
      <br>
      Reviewer - <%= @review.reviewer %>
      <br>
      Email - <%= @review.email %>
      <br>
      Created at - <%= @review.created_at %>
      <hr style="height:1px">
    </small>
    </h6>
  </div>
</div>
<%= render @review.comments %>
<%= render 'comments/form', comment: Comment.new, review: @review, movie: @review.movie %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review for </h1>
<h1><% @movie.title %></h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for writing review</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <%= render partial: 'form', locals: { review: @review } %>
 </div>

app/views/reviews/show.html.erb
<% @reviews.each do |review| %>
<div class="media">
  <div class="media-body">
    <h6 class="media-heading">
      <div class="reviews">
        <p class="inline"><%= review.body %>
        <div class="star-rating" data-score= <%= review.score %> ></div></p>
      </div>
      <br>
      Title - <%= review.movie.title %>
      <hr style="height:1px">
    </h6>
  </div>
</div>
<% end %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>